packages:
  - 'frontend'
  - 'backend/gateway'
  - 'backend/shared'
  -  "backend/services/*"
allowBuilds:
  '@apollo/protobufjs': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@remix-run/router@1.23.3'
  - react-router-dom@6.30.4
  - react-router@6.30.4
